### ISSUE TITLE
sprofile caused my job to fail

### ISSUE THREAD

**Issue by kleag** [CEA-LIST/sprofile#1]
My slurm job was running a loop where I made `srun sprofile start` and `srun sprofile stop` after a large singularity exec. I also always run my scripts with
```bash
set -o errexit
set -o pipefail
```
A crash in sprofile caused my script to be interrupted:
```-- sprofile report (node07) --
  Time:  1 day, 0:24:49  /  3 days, 0:00:00
srun: error: node07: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "xxx/bin/sprofile", line 8, in <module>
    sys.exit(main())
  File "xxx/lib/python3.10/site-packages/sprofile/sprofile.py", line 280, in main
    cpu_load, num_cpus, memory_max, memory_limit = CGroupStats.stop(db)
  File "xxx/lib/python3.10/site-packages/sprofile/sprofile.py", line 243, in stop
    _, days, hours, minutes, seconds = map(int, run_time.groups(default="0"))
ValueError: invalid literal for int() with base 10: '1-'
### Job 189986 finished!
```

**Comment by nlgranger** [comment]
Do you have the [latest commit](https://github.com/CEA-LIST/sprofile/commit/0ec91965c2550ce9ec34585d71fa8e99258491c2)? I thought I fixed that.

**Comment by nlgranger** [comment]
My bad, I forgot to fix one of the time parsing lines. I will upload a new version to pypi soon. In the meantime you can use the git version: `pip install -U "git+https://github.com/CEA-LIST/sprofile.git"`

**Comment by kleag** [comment]
I have a script which is currently running and executed the loop several times with the 0.2.2 version from github. It has not crashed up to now. I close the issue and will reopen if it reoccurs. Thanks !
